version: "3"
services:
  flaskapi:
    container_name: flaskapi
    image: flaskapi
    # build: .
    volumes:
      - appdb:/etc/todos
    ports:
      - 3000:5000
    networks:
      - app
    # Redémarre le service quand l'environment d'exécution de docker est redémarrer
    # Ou lors d'un échec de l'environment docker
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app

# Cette section crée un disk de storage pour l'environment muti-conteneur à déployer
volumes:
  appdb:
    driver: local

# Cette section crée un réseau virtuel pour l'environment muti-conteneur à déployer
networks:
  app:
    # driver: bridge
  # frontend:
  #   # driver: bridge